name: Build and Deploy TEI Website
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update-documentation]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        uses: TartanLLama/actions-eleventy@v1.3
        with:
          install_dependencies: true
      - name: Deploy
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEIWEB_KEY }}
      - run: |
          ssh -o StrictHostKeyChecking=accept-new ${{ secrets.TEIWEB_USER }}@${{ secrets.TEIWEB_HOST }} uptime
          rsync -avz -e ssh --delete dist/ ${{ secrets.TEIWEB_USER }}@${{ secrets.TEIWEB_HOST }}:${{ secrets.TEIWEB_PATH }}